#!/usr/bin/env python3
"""Migrate one kernel-checked HOL4 theorem and persist its canonical PCUIC artifact."""
from __future__ import annotations

import hashlib
import json
import re
import shutil
from pathlib import Path

from hol4_pcuic_core import ROOT, export_article, load_lock
from hol4_pcuic_translate import quote_pcuic, rocq_compile, translate_article

ARTICLE = ROOT / ".metarocq/hol4-pcuic/input.art"
WORK = ROOT / ".metarocq/hol4-pcuic/work"
OUT = ROOT / "generated/hol4-pcuic/qualification"


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def discover_imported_symbol(path: Path) -> str:
    text = path.read_text()
    decl = re.compile(
        r"^\s*(?:Definition|Theorem|Lemma|Fact|Corollary|Proposition)\s+"
        r"([A-Za-z][A-Za-z0-9_\']*)\b",
        re.MULTILINE,
    )
    names = decl.findall(text)
    preferred = [name for name in names if name.startswith("thm_")]
    candidates = preferred or names
    if not candidates:
        raise ValueError("no generated Rocq declaration found in imported.v")
    return candidates[-1]


def copy_artifacts() -> dict[str, str]:
    OUT.mkdir(parents=True, exist_ok=True)
    for p in OUT.iterdir():
        if p.is_dir():
            shutil.rmtree(p)
        else:
            p.unlink()

    copied: dict[str, str] = {}
    inputs = [
        ARTICLE,
        WORK / "imported.raw.dk",
        WORK / "imported.dk",
        WORK / "hol.dk",
        WORK / "coq.v",
        WORK / "hol.v",
        WORK / "imported.v",
        WORK / "coq-hol-light-mapping-report.json",
        WORK / "coq.vo",
        WORK / "hol.vo",
        WORK / "imported.vo",
        WORK / "QuoteImported.v",
        WORK / "QuoteImported.vo",
    ]
    for src in inputs:
        if not src.is_file():
            raise ValueError(f"missing required migration artifact: {src}")
        dst = OUT / src.name
        shutil.copy2(src, dst)
        copied[dst.name] = sha(dst)
    return copied


def main() -> int:
    lock = load_lock()
    ARTICLE.parent.mkdir(parents=True, exist_ok=True)

    exported = export_article(
        lock,
        theory_dir=Path("formal/hol4"),
        theory="MetaRocqMigrationSmoke",
        theorem="integer_interval",
        article=ARTICLE,
        timeout=1800,
    )
    translated = translate_article(lock, article=ARTICLE, work=WORK, timeout=1800)
    kernel = rocq_compile(WORK, 1800)

    symbol = discover_imported_symbol(WORK / "imported.v")
    qualified = f"Hol4Imported.imported.{symbol}"
    quoted = quote_pcuic(
        lock,
        work=WORK,
        import_symbol=qualified,
        output_name="hol4_imported_pcuic",
        timeout=1800,
    )
    copied = copy_artifacts()

    manifest = {
        "schema": 1,
        "status": "PCUIC_GENERATED",
        "source": {
            "hol4_theory": "MetaRocqMigrationSmoke",
            "hol4_theorem": "integer_interval",
            "claim": "qualification theorem reused from the qualified Aegis HOL4/Z3 pattern; not the full MetaRocq-rs metatheory",
        },
        "transport": {
            "opentheory": exported,
            "dedukti_rocq": translated,
            "rocq_kernel": kernel,
        },
        "canonical": {
            "representation": "MetaRocq.PCUIC.PCUICProgram.pcuic_program",
            "definition": "Hol4Imported.QuoteImported.hol4_imported_pcuic",
            "source_symbol": qualified,
            "quotation": quoted,
            "claim": "the accepted final migration artifact is the MetaRocq-generated PCUIC program, not the OpenTheory, Dedukti, or generated Rocq transport representation",
        },
        "files": copied,
    }
    (OUT / "manifest.json").write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    (OUT / "PCUIC.md").write_text(
        "# Canonical migrated proof artifact\n\n"
        "QuoteImported.vo contains hol4_imported_pcuic of type "
        "MetaRocq.PCUIC.PCUICProgram.pcuic_program, generated by "
        "MetaRocq.TemplatePCUIC.PCUICTemplateMonad.Core.tmQuoteRecTransp "
        "after independent Lambdapi/Dedukti and Rocq-kernel checking.\n\n"
        "The OpenTheory article, Dedukti term and generated Rocq source are retained "
        "only for reproducible provenance and replay.\n"
    )
    print(json.dumps({"status": "PCUIC_GENERATED", "definition": manifest["canonical"]["definition"]}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
