(* Every mapped module; unavailable artifacts block compilation. *)
Require Import Corelib.Array.ArrayAxioms.
Require Import Corelib.Array.PrimArray.
Require Import Corelib.BinNums.IntDef.
Require Import Corelib.BinNums.NatDef.
Require Import Corelib.BinNums.PosDef.
Require Import Corelib.Classes.CMorphisms.
Require Import Corelib.Classes.CRelationClasses.
Require Import Corelib.Classes.Equivalence.
Require Import Corelib.Classes.Init.
Require Import Corelib.Classes.Morphisms.
Require Import Corelib.Classes.Morphisms_Prop.
Require Import Corelib.Classes.RelationClasses.
Require Import Corelib.Classes.SetoidTactics.
Require Import Corelib.Compat.Coq818.
Require Import Corelib.Compat.Coq819.
Require Import Corelib.Compat.Coq820.
Require Import Corelib.Compat.Rocq90.
Require Import Corelib.Floats.FloatAxioms.
Require Import Corelib.Floats.FloatClass.
Require Import Corelib.Floats.FloatOps.
Require Import Corelib.Floats.PrimFloat.
Require Import Corelib.Floats.SpecFloat.
Require Import Corelib.Init.Byte.
Require Import Corelib.Init.Datatypes.
Require Import Corelib.Init.Decimal.
Require Import Corelib.Init.Hexadecimal.
Require Import Corelib.Init.Logic.
Require Import Corelib.Init.Ltac.
Require Import Corelib.Init.Nat.
Require Import Corelib.Init.Notations.
Require Import Corelib.Init.Number.
Require Import Corelib.Init.Peano.
Require Import Corelib.Init.Prelude.
Require Import Corelib.Init.Specif.
Require Import Corelib.Init.Sumbool.
Require Import Corelib.Init.Tactics.
Require Import Corelib.Init.Tauto.
Require Import Corelib.Init.Wf.
Require Import Corelib.Lists.ListDef.
Require Import Corelib.Numbers.BinNums.
Require Import Corelib.Numbers.Cyclic.Int63.CarryType.
Require Import Corelib.Numbers.Cyclic.Int63.PrimInt63.
Require Import Corelib.Numbers.Cyclic.Int63.Sint63Axioms.
Require Import Corelib.Numbers.Cyclic.Int63.Uint63Axioms.
Require Import Corelib.Program.Basics.
Require Import Corelib.Program.Tactics.
Require Import Corelib.Program.Utils.
Require Import Corelib.Program.Wf.
Require Import Corelib.Relations.Relation_Definitions.
Require Import Corelib.Setoids.Setoid.
Require Import Corelib.Strings.PrimString.
Require Import Corelib.Strings.PrimStringAxioms.
Require Import Corelib.derive.Derive.
Require Import Corelib.extraction.ExtrHaskellBasic.
Require Import Corelib.extraction.ExtrOcamlBasic.
Require Import Corelib.extraction.Extraction.
Require Import Corelib.ssr.ssrbool.
Require Import Corelib.ssr.ssrclasses.
Require Import Corelib.ssr.ssreflect.
Require Import Corelib.ssr.ssrfun.
Require Import Corelib.ssr.ssrsetoid.
Require Import Corelib.ssr.ssrunder.
Require Import Corelib.ssrmatching.ssrmatching.
Require Import Ltac2.Array.
Require Import Ltac2.Bool.
Require Import Ltac2.Char.
Require Import Ltac2.Compat.Coq818.
Require Import Ltac2.Compat.Coq819.
Require Import Ltac2.Constant.
Require Import Ltac2.Constr.
Require Import Ltac2.Constructor.
Require Import Ltac2.Control.
Require Import Ltac2.Env.
Require Import Ltac2.Evar.
Require Import Ltac2.FMap.
Require Import Ltac2.FSet.
Require Import Ltac2.Float.
Require Import Ltac2.Fresh.
Require Import Ltac2.Ident.
Require Import Ltac2.Ind.
Require Import Ltac2.Init.
Require Import Ltac2.Int.
Require Import Ltac2.Lazy.
Require Import Ltac2.List.
Require Import Ltac2.Ltac1.
Require Import Ltac2.Ltac1CompatNotations.
Require Import Ltac2.Ltac2.
Require Import Ltac2.Message.
Require Import Ltac2.Meta.
Require Import Ltac2.Notations.
Require Import Ltac2.Option.
Require Import Ltac2.Pattern.
Require Import Ltac2.Printf.
Require Import Ltac2.Proj.
Require Import Ltac2.Pstring.
Require Import Ltac2.RedFlags.
Require Import Ltac2.Ref.
Require Import Ltac2.Rewrite.
Require Import Ltac2.Std.
Require Import Ltac2.String.
Require Import Ltac2.TransparentState.
Require Import Ltac2.Uint63.
Require Import Ltac2.Unification.
Require Import MetaRocq.Common.BasicAst.
Require Import MetaRocq.Common.EnvMap.
Require Import MetaRocq.Common.Environment.
Require Import MetaRocq.Common.EnvironmentReflect.
Require Import MetaRocq.Common.EnvironmentTyping.
Require Import MetaRocq.Common.Kernames.
Require Import MetaRocq.Common.MonadBasicAst.
Require Import MetaRocq.Common.Primitive.
Require Import MetaRocq.Common.Reflect.
Require Import MetaRocq.Common.Transform.
Require Import MetaRocq.Common.Universes.
Require Import MetaRocq.Common.UniversesDec.
Require Import MetaRocq.Common.config.
Require Import MetaRocq.Common.uGraph.
Require Import MetaRocq.Erasure.EArities.
Require Import MetaRocq.Erasure.EAst.
Require Import MetaRocq.Erasure.EAstUtils.
Require Import MetaRocq.Erasure.EBeta.
Require Import MetaRocq.Erasure.ECSubst.
Require Import MetaRocq.Erasure.ECoInductiveToInductive.
Require Import MetaRocq.Erasure.EConstructorsAsBlocks.
Require Import MetaRocq.Erasure.EDeps.
Require Import MetaRocq.Erasure.EEnvMap.
Require Import MetaRocq.Erasure.EEtaExpanded.
Require Import MetaRocq.Erasure.EEtaExpandedFix.
Require Import MetaRocq.Erasure.EExtends.
Require Import MetaRocq.Erasure.EGenericGlobalMap.
Require Import MetaRocq.Erasure.EGenericMapEnv.
Require Import MetaRocq.Erasure.EGlobalEnv.
Require Import MetaRocq.Erasure.EGlobalFragment.
Require Import MetaRocq.Erasure.EImplementBox.
Require Import MetaRocq.Erasure.EInduction.
Require Import MetaRocq.Erasure.EInlineProjections.
Require Import MetaRocq.Erasure.EInlining.
Require Import MetaRocq.Erasure.ELiftSubst.
Require Import MetaRocq.Erasure.EOptimizePropDiscr.
Require Import MetaRocq.Erasure.EPretty.
Require Import MetaRocq.Erasure.EPrimitive.
Require Import MetaRocq.Erasure.EProgram.
Require Import MetaRocq.Erasure.EReflect.
Require Import MetaRocq.Erasure.ERemapInductives.
Require Import MetaRocq.Erasure.ERemoveParams.
Require Import MetaRocq.Erasure.EReorderCstrs.
Require Import MetaRocq.Erasure.ESpineView.
Require Import MetaRocq.Erasure.ESubstitution.
Require Import MetaRocq.Erasure.EUnboxing.
Require Import MetaRocq.Erasure.EWcbvEval.
Require Import MetaRocq.Erasure.EWcbvEvalCstrsAsBlocksFixLambdaInd.
Require Import MetaRocq.Erasure.EWcbvEvalCstrsAsBlocksInd.
Require Import MetaRocq.Erasure.EWcbvEvalEtaInd.
Require Import MetaRocq.Erasure.EWcbvEvalInd.
Require Import MetaRocq.Erasure.EWcbvEvalNamed.
Require Import MetaRocq.Erasure.EWellformed.
Require Import MetaRocq.Erasure.EWtAst.
Require Import MetaRocq.Erasure.ErasureCorrectness.
Require Import MetaRocq.Erasure.ErasureFunction.
Require Import MetaRocq.Erasure.ErasureFunctionProperties.
Require Import MetaRocq.Erasure.ErasureProperties.
Require Import MetaRocq.Erasure.Extract.
Require Import MetaRocq.Erasure.Prelim.
Require Import MetaRocq.Erasure.Typed.Annotations.
Require Import MetaRocq.Erasure.Typed.Certifying.
Require Import MetaRocq.Erasure.Typed.CertifyingBeta.
Require Import MetaRocq.Erasure.Typed.CertifyingEta.
Require Import MetaRocq.Erasure.Typed.CertifyingInlining.
Require Import MetaRocq.Erasure.Typed.ClosedAux.
Require Import MetaRocq.Erasure.Typed.Erasure.
Require Import MetaRocq.Erasure.Typed.ErasureCorrectness.
Require Import MetaRocq.Erasure.Typed.ExAst.
Require Import MetaRocq.Erasure.Typed.Extraction.
Require Import MetaRocq.Erasure.Typed.ExtractionCorrectness.
Require Import MetaRocq.Erasure.Typed.Optimize.
Require Import MetaRocq.Erasure.Typed.OptimizeCorrectness.
Require Import MetaRocq.Erasure.Typed.OptimizePropDiscr.
Require Import MetaRocq.Erasure.Typed.Transform.
Require Import MetaRocq.Erasure.Typed.TypeAnnotations.
Require Import MetaRocq.Erasure.Typed.Utils.
Require Import MetaRocq.Erasure.Typed.WcbvEvalAux.
Require Import MetaRocq.ErasurePlugin.ETransform.
Require Import MetaRocq.ErasurePlugin.Erasure.
Require Import MetaRocq.ErasurePlugin.ErasureCorrectness.
Require Import MetaRocq.ErasurePlugin.Extraction.
Require Import MetaRocq.ErasurePlugin.Loader.
Require Import MetaRocq.Examples.add_constructor.
Require Import MetaRocq.Examples.constructor_tac.
Require Import MetaRocq.Examples.demo.
Require Import MetaRocq.Examples.metarocq_tour.
Require Import MetaRocq.Examples.metarocq_tour_prelude.
Require Import MetaRocq.Examples.tauto.
Require Import MetaRocq.Examples.typing_correctness.
Require Import MetaRocq.ExtractedPluginDemo.Extraction.
Require Import MetaRocq.ExtractedPluginDemo.Lens.
Require Import MetaRocq.ExtractedPluginDemo.Loader.
Require Import MetaRocq.ExtractedPluginDemo.MyPlugin.
Require Import MetaRocq.PCUIC.Bidirectional.BDFromPCUIC.
Require Import MetaRocq.PCUIC.Bidirectional.BDStrengthening.
Require Import MetaRocq.PCUIC.Bidirectional.BDToPCUIC.
Require Import MetaRocq.PCUIC.Bidirectional.BDTyping.
Require Import MetaRocq.PCUIC.Bidirectional.BDUnique.
Require Import MetaRocq.PCUIC.Conversion.PCUICClosedConv.
Require Import MetaRocq.PCUIC.Conversion.PCUICInstConv.
Require Import MetaRocq.PCUIC.Conversion.PCUICNamelessConv.
Require Import MetaRocq.PCUIC.Conversion.PCUICOnFreeVarsConv.
Require Import MetaRocq.PCUIC.Conversion.PCUICRenameConv.
Require Import MetaRocq.PCUIC.Conversion.PCUICUnivSubstitutionConv.
Require Import MetaRocq.PCUIC.Conversion.PCUICWeakeningConfigConv.
Require Import MetaRocq.PCUIC.Conversion.PCUICWeakeningConv.
Require Import MetaRocq.PCUIC.Conversion.PCUICWeakeningEnvConv.
Require Import MetaRocq.PCUIC.PCUICAlpha.
Require Import MetaRocq.PCUIC.PCUICArities.
Require Import MetaRocq.PCUIC.PCUICAst.
Require Import MetaRocq.PCUIC.PCUICCSubst.
Require Import MetaRocq.PCUIC.PCUICCanonicity.
Require Import MetaRocq.PCUIC.PCUICCasesContexts.
Require Import MetaRocq.PCUIC.PCUICCasesHelper.
Require Import MetaRocq.PCUIC.PCUICClassification.
Require Import MetaRocq.PCUIC.PCUICConfluence.
Require Import MetaRocq.PCUIC.PCUICConsistency.
Require Import MetaRocq.PCUIC.PCUICContextConversion.
Require Import MetaRocq.PCUIC.PCUICContextReduction.
Require Import MetaRocq.PCUIC.PCUICContextSubst.
Require Import MetaRocq.PCUIC.PCUICContexts.
Require Import MetaRocq.PCUIC.PCUICConvCumInversion.
Require Import MetaRocq.PCUIC.PCUICConversion.
Require Import MetaRocq.PCUIC.PCUICCumulProp.
Require Import MetaRocq.PCUIC.PCUICCumulativity.
Require Import MetaRocq.PCUIC.PCUICCumulativitySpec.
Require Import MetaRocq.PCUIC.PCUICElimination.
Require Import MetaRocq.PCUIC.PCUICEquality.
Require Import MetaRocq.PCUIC.PCUICEtaExpand.
Require Import MetaRocq.PCUIC.PCUICExpandLets.
Require Import MetaRocq.PCUIC.PCUICExpandLetsCorrectness.
Require Import MetaRocq.PCUIC.PCUICFirstorder.
Require Import MetaRocq.PCUIC.PCUICGeneration.
Require Import MetaRocq.PCUIC.PCUICGlobalEnv.
Require Import MetaRocq.PCUIC.PCUICGuardCondition.
Require Import MetaRocq.PCUIC.PCUICInductiveInversion.
Require Import MetaRocq.PCUIC.PCUICInductives.
Require Import MetaRocq.PCUIC.PCUICInversion.
Require Import MetaRocq.PCUIC.PCUICLoader.
Require Import MetaRocq.PCUIC.PCUICMonadAst.
Require Import MetaRocq.PCUIC.PCUICNormal.
Require Import MetaRocq.PCUIC.PCUICNormalization.
Require Import MetaRocq.PCUIC.PCUICParallelReduction.
Require Import MetaRocq.PCUIC.PCUICParallelReductionConfluence.
Require Import MetaRocq.PCUIC.PCUICPrincipality.
Require Import MetaRocq.PCUIC.PCUICProgram.
Require Import MetaRocq.PCUIC.PCUICProgress.
Require Import MetaRocq.PCUIC.PCUICRedTypeIrrelevance.
Require Import MetaRocq.PCUIC.PCUICReduction.
Require Import MetaRocq.PCUIC.PCUICSN.
Require Import MetaRocq.PCUIC.PCUICSR.
Require Import MetaRocq.PCUIC.PCUICSafeLemmata.
Require Import MetaRocq.PCUIC.PCUICSigmaCalculus.
Require Import MetaRocq.PCUIC.PCUICSpine.
Require Import MetaRocq.PCUIC.PCUICSubstitution.
Require Import MetaRocq.PCUIC.PCUICTelescopes.
Require Import MetaRocq.PCUIC.PCUICTypedAst.
Require Import MetaRocq.PCUIC.PCUICTyping.
Require Import MetaRocq.PCUIC.PCUICUnivLevels.
Require Import MetaRocq.PCUIC.PCUICValidity.
Require Import MetaRocq.PCUIC.PCUICWcbvEval.
Require Import MetaRocq.PCUIC.PCUICWeakeningConfig.
Require Import MetaRocq.PCUIC.PCUICWeakeningConfigSN.
Require Import MetaRocq.PCUIC.PCUICWeakeningEnv.
Require Import MetaRocq.PCUIC.PCUICWeakeningEnvSN.
Require Import MetaRocq.PCUIC.PCUICWellScopedCumulativity.
Require Import MetaRocq.PCUIC.PCUICWfCases.
Require Import MetaRocq.PCUIC.PCUICWfUniverses.
Require Import MetaRocq.PCUIC.PCUICWtCumulativity.
Require Import MetaRocq.PCUIC.Syntax.PCUICCases.
Require Import MetaRocq.PCUIC.Syntax.PCUICClosed.
Require Import MetaRocq.PCUIC.Syntax.PCUICDepth.
Require Import MetaRocq.PCUIC.Syntax.PCUICInduction.
Require Import MetaRocq.PCUIC.Syntax.PCUICInstDef.
Require Import MetaRocq.PCUIC.Syntax.PCUICLiftSubst.
Require Import MetaRocq.PCUIC.Syntax.PCUICNamelessDef.
Require Import MetaRocq.PCUIC.Syntax.PCUICOnFreeVars.
Require Import MetaRocq.PCUIC.Syntax.PCUICPosition.
Require Import MetaRocq.PCUIC.Syntax.PCUICReflect.
Require Import MetaRocq.PCUIC.Syntax.PCUICRenameDef.
Require Import MetaRocq.PCUIC.Syntax.PCUICTactics.
Require Import MetaRocq.PCUIC.Syntax.PCUICUnivSubst.
Require Import MetaRocq.PCUIC.Syntax.PCUICViews.
Require Import MetaRocq.PCUIC.Typing.PCUICClosedTyp.
Require Import MetaRocq.PCUIC.Typing.PCUICContextConversionTyp.
Require Import MetaRocq.PCUIC.Typing.PCUICInstTyp.
Require Import MetaRocq.PCUIC.Typing.PCUICNamelessTyp.
Require Import MetaRocq.PCUIC.Typing.PCUICRenameTyp.
Require Import MetaRocq.PCUIC.Typing.PCUICUnivSubstitutionTyp.
Require Import MetaRocq.PCUIC.Typing.PCUICWeakeningConfigTyp.
Require Import MetaRocq.PCUIC.Typing.PCUICWeakeningEnvTyp.
Require Import MetaRocq.PCUIC.Typing.PCUICWeakeningTyp.
Require Import MetaRocq.PCUIC.utils.PCUICAstUtils.
Require Import MetaRocq.PCUIC.utils.PCUICOnOne.
Require Import MetaRocq.PCUIC.utils.PCUICPretty.
Require Import MetaRocq.PCUIC.utils.PCUICPrimitive.
Require Import MetaRocq.PCUIC.utils.PCUICSize.
Require Import MetaRocq.PCUIC.utils.PCUICUtils.
Require Import MetaRocq.Quotation.CommonUtils.
Require Import MetaRocq.Quotation.ToPCUIC.All.
Require Import MetaRocq.Quotation.ToPCUIC.Common.BasicAst.
Require Import MetaRocq.Quotation.ToPCUIC.Common.Environment.
Require Import MetaRocq.Quotation.ToPCUIC.Common.EnvironmentTyping.
Require Import MetaRocq.Quotation.ToPCUIC.Common.Kernames.
Require Import MetaRocq.Quotation.ToPCUIC.Common.Primitive.
Require Import MetaRocq.Quotation.ToPCUIC.Common.Reflect.
Require Import MetaRocq.Quotation.ToPCUIC.Common.Transform.
Require Import MetaRocq.Quotation.ToPCUIC.Common.Universes.
Require Import MetaRocq.Quotation.ToPCUIC.Common.config.
Require Import MetaRocq.Quotation.ToPCUIC.Equations.
Require Import MetaRocq.Quotation.ToPCUIC.Equations.Type.
Require Import MetaRocq.Quotation.ToPCUIC.Init.
Require Import MetaRocq.Quotation.ToPCUIC.PCUIC.Induction.
Require Import MetaRocq.Quotation.ToPCUIC.PCUIC.PCUICAst.
Require Import MetaRocq.Quotation.ToPCUIC.PCUIC.PCUICCumulativitySpec.
Require Import MetaRocq.Quotation.ToPCUIC.PCUIC.PCUICEquality.
Require Import MetaRocq.Quotation.ToPCUIC.PCUIC.PCUICReduction.
Require Import MetaRocq.Quotation.ToPCUIC.PCUIC.PCUICTyping.
Require Import MetaRocq.Quotation.ToPCUIC.PCUIC.Syntax.PCUICCases.
Require Import MetaRocq.Quotation.ToPCUIC.PCUIC.utils.PCUICAstUtils.
Require Import MetaRocq.Quotation.ToPCUIC.PCUIC.utils.PCUICPrimitive.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.Common.Environment.Sig.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.Common.EnvironmentTyping.Sig.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.Common.Kernames.Instances.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.Common.Kernames.Kername.Instances.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.Common.Kernames.KernameMap.Instances.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.Common.Kernames.KernameMapDecide.Instances.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.Common.Kernames.KernameMapExtraFact.Instances.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.Common.Kernames.KernameMapFact.Instances.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.Common.Kernames.KernameSet.Instances.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.Common.Kernames.KernameSetExtraDecide.Instances.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.Common.Kernames.KernameSetExtraOrdProp.Instances.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.Common.Kernames.KernameSetOrdProp.Instances.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.Common.Universes.ConstraintSet.Instances.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.Common.Universes.ConstraintSetExtraDecide.Instances.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.Common.Universes.ConstraintSetExtraOrdProp.Instances.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.Common.Universes.ConstraintSetOrdProp.Instances.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.Common.Universes.Instances.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.Common.Universes.Level.Instances.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.Common.Universes.LevelExpr.Instances.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.Common.Universes.LevelExprSet.Instances.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.Common.Universes.LevelExprSetExtraOrdProp.Instances.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.Common.Universes.LevelExprSetOrdProp.Instances.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.Common.Universes.LevelSet.Instances.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.Common.Universes.LevelSetExtraDecide.Instances.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.Common.Universes.LevelSetExtraOrdProp.Instances.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.Common.Universes.LevelSetOrdProp.Instances.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.Common.Universes.UnivConstraint.Instances.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.PCUIC.PCUICAst.Instances.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.PCUIC.PCUICAst.PCUICConversion.Instances.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.PCUIC.PCUICAst.PCUICEnvTyping.Instances.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.PCUIC.PCUICAst.PCUICEnvironment.Instances.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.PCUIC.PCUICAst.PCUICEnvironmentHelper.Instances.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.PCUIC.PCUICAst.PCUICGlobalMaps.Instances.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.PCUIC.PCUICAst.PCUICLookup.Instances.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.PCUIC.PCUICAst.PCUICTerm.Instances.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.PCUIC.PCUICAst.PCUICTermUtils.Instances.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.PCUIC.PCUICCumulativity.Instances.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.PCUIC.PCUICCumulativity.PCUICConversionParAlgo.Instances.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.PCUIC.PCUICCumulativitySpec.Instances.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.PCUIC.PCUICCumulativitySpec.PCUICConversionParSpec.Instances.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.PCUIC.PCUICTyping.Instances.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.PCUIC.PCUICTyping.PCUICDeclarationTyping.Instances.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.PCUIC.PCUICTyping.PCUICTypingDef.Instances.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.PCUIC.Syntax.PCUICReflect.Instances.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.PCUIC.Syntax.PCUICReflect.PCUICEnvironmentDecide.Instances.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.PCUIC.Syntax.PCUICReflect.PCUICTermDecide.Instances.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.Stdlib.FSets.FMapAVL.Sig.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.Stdlib.FSets.FMapFacts.Sig.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.Stdlib.FSets.FMapInterface.Sig.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.Stdlib.FSets.FMapList.Sig.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.Stdlib.MSets.MSetAVL.Sig.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.Stdlib.MSets.MSetDecide.Sig.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.Stdlib.MSets.MSetFacts.Sig.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.Stdlib.MSets.MSetInterface.Sig.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.Stdlib.MSets.MSetList.Sig.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.Stdlib.MSets.MSetProperties.Sig.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.Stdlib.Structures.Equalities.Sig.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.Stdlib.Structures.Orders.Sig.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.Stdlib.Structures.OrdersAlt.Sig.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.Stdlib.Structures.OrdersFacts.Sig.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.Stdlib.Structures.OrdersTac.Sig.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.Utils.MRFSets.Sig.
Require Import MetaRocq.Quotation.ToPCUIC.QuotationOf.Utils.MRMSets.Sig.
Require Import MetaRocq.Quotation.ToPCUIC.Stdlib.Bool.
Require Import MetaRocq.Quotation.ToPCUIC.Stdlib.FSets.
Require Import MetaRocq.Quotation.ToPCUIC.Stdlib.Floats.
Require Import MetaRocq.Quotation.ToPCUIC.Stdlib.Init.
Require Import MetaRocq.Quotation.ToPCUIC.Stdlib.Lists.
Require Import MetaRocq.Quotation.ToPCUIC.Stdlib.MSets.
Require Import MetaRocq.Quotation.ToPCUIC.Stdlib.Numbers.
Require Import MetaRocq.Quotation.ToPCUIC.Stdlib.Strings.
Require Import MetaRocq.Quotation.ToPCUIC.Stdlib.ssr.
Require Import MetaRocq.Quotation.ToPCUIC.Utils.All_Forall.
Require Import MetaRocq.Quotation.ToPCUIC.Utils.ByteCompare.
Require Import MetaRocq.Quotation.ToPCUIC.Utils.ByteCompareSpec.
Require Import MetaRocq.Quotation.ToPCUIC.Utils.ByteCompare_opt.
Require Import MetaRocq.Quotation.ToPCUIC.Utils.LibHypsNaming.
Require Import MetaRocq.Quotation.ToPCUIC.Utils.MRArith.
Require Import MetaRocq.Quotation.ToPCUIC.Utils.MRCompare.
Require Import MetaRocq.Quotation.ToPCUIC.Utils.MREquality.
Require Import MetaRocq.Quotation.ToPCUIC.Utils.MRList.
Require Import MetaRocq.Quotation.ToPCUIC.Utils.MROption.
Require Import MetaRocq.Quotation.ToPCUIC.Utils.MRPred.
Require Import MetaRocq.Quotation.ToPCUIC.Utils.MRPrelude.
Require Import MetaRocq.Quotation.ToPCUIC.Utils.MRProd.
Require Import MetaRocq.Quotation.ToPCUIC.Utils.MRReflect.
Require Import MetaRocq.Quotation.ToPCUIC.Utils.MRRelations.
Require Import MetaRocq.Quotation.ToPCUIC.Utils.MRSquash.
Require Import MetaRocq.Quotation.ToPCUIC.Utils.MRString.
Require Import MetaRocq.Quotation.ToPCUIC.Utils.MRUtils.
Require Import MetaRocq.Quotation.ToPCUIC.Utils.ReflectEq.
Require Import MetaRocq.Quotation.ToPCUIC.Utils.bytestring.
Require Import MetaRocq.Quotation.ToPCUIC.Utils.monad_utils.
Require Import MetaRocq.Quotation.ToPCUIC.Utils.utils.
Require Import MetaRocq.Quotation.ToTemplate.All.
Require Import MetaRocq.Quotation.ToTemplate.Common.BasicAst.
Require Import MetaRocq.Quotation.ToTemplate.Common.Environment.
Require Import MetaRocq.Quotation.ToTemplate.Common.EnvironmentTyping.
Require Import MetaRocq.Quotation.ToTemplate.Common.Kernames.
Require Import MetaRocq.Quotation.ToTemplate.Common.Primitive.
Require Import MetaRocq.Quotation.ToTemplate.Common.Reflect.
Require Import MetaRocq.Quotation.ToTemplate.Common.Transform.
Require Import MetaRocq.Quotation.ToTemplate.Common.Universes.
Require Import MetaRocq.Quotation.ToTemplate.Common.config.
Require Import MetaRocq.Quotation.ToTemplate.Equations.
Require Import MetaRocq.Quotation.ToTemplate.Equations.Type.
Require Import MetaRocq.Quotation.ToTemplate.Init.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Common.Environment.Sig.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Common.EnvironmentTyping.Sig.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Common.Kernames.Instances.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Common.Kernames.Kername.Instances.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Common.Kernames.KernameMap.Instances.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Common.Kernames.KernameMapDecide.Instances.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Common.Kernames.KernameMapExtraFact.Instances.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Common.Kernames.KernameMapFact.Instances.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Common.Kernames.KernameSet.Instances.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Common.Kernames.KernameSetExtraDecide.Instances.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Common.Kernames.KernameSetExtraOrdProp.Instances.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Common.Kernames.KernameSetOrdProp.Instances.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Common.Universes.ConstraintSet.Instances.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Common.Universes.ConstraintSetExtraDecide.Instances.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Common.Universes.ConstraintSetExtraOrdProp.Instances.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Common.Universes.ConstraintSetOrdProp.Instances.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Common.Universes.Instances.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Common.Universes.Level.Instances.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Common.Universes.LevelExpr.Instances.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Common.Universes.LevelExprSet.Instances.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Common.Universes.LevelExprSetExtraOrdProp.Instances.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Common.Universes.LevelExprSetOrdProp.Instances.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Common.Universes.LevelSet.Instances.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Common.Universes.LevelSetExtraDecide.Instances.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Common.Universes.LevelSetExtraOrdProp.Instances.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Common.Universes.LevelSetOrdProp.Instances.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Common.Universes.UnivConstraint.Instances.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Stdlib.FSets.FMapAVL.Sig.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Stdlib.FSets.FMapFacts.Sig.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Stdlib.FSets.FMapInterface.Sig.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Stdlib.FSets.FMapList.Sig.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Stdlib.MSets.MSetAVL.Sig.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Stdlib.MSets.MSetDecide.Sig.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Stdlib.MSets.MSetFacts.Sig.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Stdlib.MSets.MSetInterface.Sig.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Stdlib.MSets.MSetList.Sig.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Stdlib.MSets.MSetProperties.Sig.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Stdlib.Structures.Equalities.Sig.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Stdlib.Structures.Orders.Sig.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Stdlib.Structures.OrdersAlt.Sig.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Stdlib.Structures.OrdersFacts.Sig.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Stdlib.Structures.OrdersTac.Sig.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Template.Ast.Env.Instances.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Template.Ast.EnvHelper.Instances.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Template.Ast.Instances.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Template.Ast.TemplateLookup.Instances.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Template.Ast.TemplateTerm.Instances.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Template.Ast.TemplateTermUtils.Instances.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Template.ReflectAst.EnvDecide.Instances.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Template.ReflectAst.Instances.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Template.ReflectAst.TemplateTermDecide.Instances.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Template.Typing.Instances.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Template.Typing.TemplateConversion.Instances.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Template.Typing.TemplateConversionPar.Instances.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Template.Typing.TemplateDeclarationTyping.Instances.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Template.Typing.TemplateEnvTyping.Instances.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Template.Typing.TemplateGlobalMaps.Instances.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Template.Typing.TemplateTyping.Instances.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Utils.MRFSets.Sig.
Require Import MetaRocq.Quotation.ToTemplate.QuotationOf.Utils.MRMSets.Sig.
Require Import MetaRocq.Quotation.ToTemplate.Stdlib.Bool.
Require Import MetaRocq.Quotation.ToTemplate.Stdlib.FSets.
Require Import MetaRocq.Quotation.ToTemplate.Stdlib.Floats.
Require Import MetaRocq.Quotation.ToTemplate.Stdlib.Init.
Require Import MetaRocq.Quotation.ToTemplate.Stdlib.Lists.
Require Import MetaRocq.Quotation.ToTemplate.Stdlib.MSets.
Require Import MetaRocq.Quotation.ToTemplate.Stdlib.Numbers.
Require Import MetaRocq.Quotation.ToTemplate.Stdlib.Strings.
Require Import MetaRocq.Quotation.ToTemplate.Stdlib.ssr.
Require Import MetaRocq.Quotation.ToTemplate.Template.Ast.
Require Import MetaRocq.Quotation.ToTemplate.Template.AstUtils.
Require Import MetaRocq.Quotation.ToTemplate.Template.Induction.
Require Import MetaRocq.Quotation.ToTemplate.Template.LiftSubst.
Require Import MetaRocq.Quotation.ToTemplate.Template.ReflectAst.
Require Import MetaRocq.Quotation.ToTemplate.Template.TermEquality.
Require Import MetaRocq.Quotation.ToTemplate.Template.Typing.
Require Import MetaRocq.Quotation.ToTemplate.Template.TypingWf.
Require Import MetaRocq.Quotation.ToTemplate.Template.UnivSubst.
Require Import MetaRocq.Quotation.ToTemplate.Template.WfAst.
Require Import MetaRocq.Quotation.ToTemplate.Utils.All_Forall.
Require Import MetaRocq.Quotation.ToTemplate.Utils.ByteCompare.
Require Import MetaRocq.Quotation.ToTemplate.Utils.ByteCompareSpec.
Require Import MetaRocq.Quotation.ToTemplate.Utils.ByteCompare_opt.
Require Import MetaRocq.Quotation.ToTemplate.Utils.LibHypsNaming.
Require Import MetaRocq.Quotation.ToTemplate.Utils.MRArith.
Require Import MetaRocq.Quotation.ToTemplate.Utils.MRCompare.
Require Import MetaRocq.Quotation.ToTemplate.Utils.MREquality.
Require Import MetaRocq.Quotation.ToTemplate.Utils.MRList.
Require Import MetaRocq.Quotation.ToTemplate.Utils.MROption.
Require Import MetaRocq.Quotation.ToTemplate.Utils.MRPred.
Require Import MetaRocq.Quotation.ToTemplate.Utils.MRPrelude.
Require Import MetaRocq.Quotation.ToTemplate.Utils.MRProd.
Require Import MetaRocq.Quotation.ToTemplate.Utils.MRReflect.
Require Import MetaRocq.Quotation.ToTemplate.Utils.MRRelations.
Require Import MetaRocq.Quotation.ToTemplate.Utils.MRSquash.
Require Import MetaRocq.Quotation.ToTemplate.Utils.MRString.
Require Import MetaRocq.Quotation.ToTemplate.Utils.MRUtils.
Require Import MetaRocq.Quotation.ToTemplate.Utils.ReflectEq.
Require Import MetaRocq.Quotation.ToTemplate.Utils.bytestring.
Require Import MetaRocq.Quotation.ToTemplate.Utils.monad_utils.
Require Import MetaRocq.Quotation.ToTemplate.Utils.utils.
Require Import MetaRocq.SafeChecker.PCUICEqualityDec.
Require Import MetaRocq.SafeChecker.PCUICErrors.
Require Import MetaRocq.SafeChecker.PCUICRetypingEnvIrrelevance.
Require Import MetaRocq.SafeChecker.PCUICSafeChecker.
Require Import MetaRocq.SafeChecker.PCUICSafeConversion.
Require Import MetaRocq.SafeChecker.PCUICSafeReduce.
Require Import MetaRocq.SafeChecker.PCUICSafeRetyping.
Require Import MetaRocq.SafeChecker.PCUICTypeChecker.
Require Import MetaRocq.SafeChecker.PCUICWfEnv.
Require Import MetaRocq.SafeChecker.PCUICWfEnvImpl.
Require Import MetaRocq.SafeChecker.PCUICWfReduction.
Require Import MetaRocq.SafeCheckerPlugin.Extraction.
Require Import MetaRocq.SafeCheckerPlugin.Loader.
Require Import MetaRocq.SafeCheckerPlugin.SafeTemplateChecker.
Require Import MetaRocq.Template.All.
Require Import MetaRocq.Template.Ast.
Require Import MetaRocq.Template.AstUtils.
Require Import MetaRocq.Template.Checker.
Require Import MetaRocq.Template.Constants.
Require Import MetaRocq.Template.EtaExpand.
Require Import MetaRocq.Template.ExtractableLoader.
Require Import MetaRocq.Template.Extraction.
Require Import MetaRocq.Template.Induction.
Require Import MetaRocq.Template.Lib.
Require Import MetaRocq.Template.LiftSubst.
Require Import MetaRocq.Template.Loader.
Require Import MetaRocq.Template.MonadAst.
Require Import MetaRocq.Template.Normal.
Require Import MetaRocq.Template.Pretty.
Require Import MetaRocq.Template.Reduction.
Require Import MetaRocq.Template.ReflectAst.
Require Import MetaRocq.Template.TemplateCheckWf.
Require Import MetaRocq.Template.TemplateEnvMap.
Require Import MetaRocq.Template.TemplateMonad.
Require Import MetaRocq.Template.TemplateMonad.Common.
Require Import MetaRocq.Template.TemplateMonad.Core.
Require Import MetaRocq.Template.TemplateMonad.Extractable.
Require Import MetaRocq.Template.TemplateProgram.
Require Import MetaRocq.Template.TermEquality.
Require Import MetaRocq.Template.Typing.
Require Import MetaRocq.Template.TypingWf.
Require Import MetaRocq.Template.UnivSubst.
Require Import MetaRocq.Template.WcbvEval.
Require Import MetaRocq.Template.WfAst.
Require Import MetaRocq.TemplatePCUIC.Loader.
Require Import MetaRocq.TemplatePCUIC.PCUICTemplateMonad.
Require Import MetaRocq.TemplatePCUIC.PCUICTemplateMonad.Core.
Require Import MetaRocq.TemplatePCUIC.PCUICToTemplate.
Require Import MetaRocq.TemplatePCUIC.PCUICToTemplateCorrectness.
Require Import MetaRocq.TemplatePCUIC.PCUICTransform.
Require Import MetaRocq.TemplatePCUIC.TemplateMonadToPCUIC.
Require Import MetaRocq.TemplatePCUIC.TemplateToPCUIC.
Require Import MetaRocq.TemplatePCUIC.TemplateToPCUICCorrectness.
Require Import MetaRocq.TemplatePCUIC.TemplateToPCUICExpanded.
Require Import MetaRocq.TemplatePCUIC.TemplateToPCUICWcbvEval.
Require Import MetaRocq.TestSuite.CheckerTest.
Require Import MetaRocq.TestSuite.ErasureTests.
Require Import MetaRocq.TestSuite.TypeAnnotationTests.
Require Import MetaRocq.TestSuite.bug1.
Require Import MetaRocq.TestSuite.bug2.
Require Import MetaRocq.TestSuite.bug369.
Require Import MetaRocq.TestSuite.bug441.
Require Import MetaRocq.TestSuite.bug5.
Require Import MetaRocq.TestSuite.bug6.
Require Import MetaRocq.TestSuite.bug7.
Require Import MetaRocq.TestSuite.bug8.
Require Import MetaRocq.TestSuite.bug_quote_pstring.
Require Import MetaRocq.TestSuite.case.
Require Import MetaRocq.TestSuite.castprop.
Require Import MetaRocq.TestSuite.cofix.
Require Import MetaRocq.TestSuite.erasure_live_test.
Require Import MetaRocq.TestSuite.erasure_test.
Require Import MetaRocq.TestSuite.evars.
Require Import MetaRocq.TestSuite.extractable.
Require Import MetaRocq.TestSuite.hnf_ctor.
Require Import MetaRocq.TestSuite.hott_example.
Require Import MetaRocq.TestSuite.ind_fresh_univ.
Require Import MetaRocq.TestSuite.inferind.
Require Import MetaRocq.TestSuite.inferindunivs.
Require Import MetaRocq.TestSuite.int.
Require Import MetaRocq.TestSuite.issue1042.
Require Import MetaRocq.TestSuite.issue27.
Require Import MetaRocq.TestSuite.issue28.
Require Import MetaRocq.TestSuite.issue453.
Require Import MetaRocq.TestSuite.letin.
Require Import MetaRocq.TestSuite.modules_sections.
Require Import MetaRocq.TestSuite.mutind.
Require Import MetaRocq.TestSuite.opaque.
Require Import MetaRocq.TestSuite.order_rec.
Require Import MetaRocq.TestSuite.primitive.
Require Import MetaRocq.TestSuite.proj.
Require Import MetaRocq.TestSuite.quotation_notations.
Require Import MetaRocq.TestSuite.reduction_test.
Require Import MetaRocq.TestSuite.run_in_tactic.
Require Import MetaRocq.TestSuite.safechecker_test.
Require Import MetaRocq.TestSuite.self_erasure.
Require Import MetaRocq.TestSuite.sprop_tests.
Require Import MetaRocq.TestSuite.tmExistingInstance.
Require Import MetaRocq.TestSuite.tmFix.
Require Import MetaRocq.TestSuite.tmFreshName.
Require Import MetaRocq.TestSuite.tmInferInstance.
Require Import MetaRocq.TestSuite.tmQuoteModule.
Require Import MetaRocq.TestSuite.tmVariable.
Require Import MetaRocq.TestSuite.unfold.
Require Import MetaRocq.TestSuite.univ.
Require Import MetaRocq.TestSuite.unquote_evars.
Require Import MetaRocq.TestSuite.vs.
Require Import MetaRocq.Translations.MiniHoTT.
Require Import MetaRocq.Translations.MiniHoTT_paths.
Require Import MetaRocq.Translations.param_binary.
Require Import MetaRocq.Translations.param_cheap_packed.
Require Import MetaRocq.Translations.param_generous_packed.
Require Import MetaRocq.Translations.param_generous_unpacked.
Require Import MetaRocq.Translations.param_original.
Require Import MetaRocq.Translations.sigma.
Require Import MetaRocq.Translations.standard_model.
Require Import MetaRocq.Translations.times_bool_fun.
Require Import MetaRocq.Translations.times_bool_fun2.
Require Import MetaRocq.Translations.translation_utils.
Require Import MetaRocq.Utils.All_Forall.
Require Import MetaRocq.Utils.ByteCompare.
Require Import MetaRocq.Utils.ByteCompareSpec.
Require Import MetaRocq.Utils.ByteCompare_opt.
Require Import MetaRocq.Utils.LibHypsNaming.
Require Import MetaRocq.Utils.MRArith.
Require Import MetaRocq.Utils.MRCompare.
Require Import MetaRocq.Utils.MREquality.
Require Import MetaRocq.Utils.MRFSets.
Require Import MetaRocq.Utils.MRList.
Require Import MetaRocq.Utils.MRListable.
Require Import MetaRocq.Utils.MRMSets.
Require Import MetaRocq.Utils.MROption.
Require Import MetaRocq.Utils.MRPred.
Require Import MetaRocq.Utils.MRPrelude.
Require Import MetaRocq.Utils.MRProd.
Require Import MetaRocq.Utils.MRReflect.
Require Import MetaRocq.Utils.MRRelations.
Require Import MetaRocq.Utils.MRSquash.
Require Import MetaRocq.Utils.MRString.
Require Import MetaRocq.Utils.MRTactics.DestructHead.
Require Import MetaRocq.Utils.MRTactics.DestructHyps.
Require Import MetaRocq.Utils.MRTactics.FindHyp.
Require Import MetaRocq.Utils.MRTactics.GeneralizeOverHoles.
Require Import MetaRocq.Utils.MRTactics.Head.
Require Import MetaRocq.Utils.MRTactics.InHypUnderBindersDo.
Require Import MetaRocq.Utils.MRTactics.SpecializeAllWays.
Require Import MetaRocq.Utils.MRTactics.SpecializeBy.
Require Import MetaRocq.Utils.MRTactics.SpecializeUnderBindersBy.
Require Import MetaRocq.Utils.MRTactics.SplitInContext.
Require Import MetaRocq.Utils.MRTactics.UniquePose.
Require Import MetaRocq.Utils.MRTactics.Zeta1.
Require Import MetaRocq.Utils.MRUtils.
Require Import MetaRocq.Utils.MR_ExtrOCamlInt63.
Require Import MetaRocq.Utils.MR_ExtrOCamlNatInt.
Require Import MetaRocq.Utils.MR_ExtrOCamlZPosInt.
Require Import MetaRocq.Utils.ReflectEq.
Require Import MetaRocq.Utils.ResultMonad.
Require Import MetaRocq.Utils.Show.
Require Import MetaRocq.Utils.bytestring.
Require Import MetaRocq.Utils.canonicaltries.CanonicalTries.
Require Import MetaRocq.Utils.canonicaltries.String2pos.
Require Import MetaRocq.Utils.monad_utils.
Require Import MetaRocq.Utils.utils.
Require Import MetaRocq.Utils.wGraph.
Require Import Peregrine.CheckWf.
Require Import Peregrine.Config.
Require Import Peregrine.ConfigUtils.
Require Import Peregrine.CoqToLambdaBox.
Require Import Peregrine.EvalBox.
Require Import Peregrine.Extraction.
Require Import Peregrine.NameSanitize.
Require Import Peregrine.PAst.
Require Import Peregrine.Pipeline.
Require Import Peregrine.Plugin.ExtractPlugin.
Require Import Peregrine.Plugin.Loader.
Require Import Peregrine.Tests.Demo.
Require Import Peregrine.Tests.Extraction.
Require Import Peregrine.Tests.Hello.
Require Import Peregrine.Tests.Map.
Require Import Peregrine.Tests.Mutual.
Require Import Peregrine.Tests.Nat.
Require Import Peregrine.Tests.OddEven.
Require Import Peregrine.Unicode.
Require Import Peregrine.UnicodeXID.
Require Import Peregrine.Utils.
Require Import Peregrine.backends.ASTBackend.
Require Import Peregrine.backends.CBackend.
Require Import Peregrine.backends.CakeMLBackend.
Require Import Peregrine.backends.CertiRocqBackend.
Require Import Peregrine.backends.ElmBackend.
Require Import Peregrine.backends.EvalBackend.
Require Import Peregrine.backends.OCamlBackend.
Require Import Peregrine.backends.RustBackend.
Require Import Peregrine.backends.WasmBackend.
Require Import Peregrine.erasure.EImplementLazyForce.
Require Import Peregrine.erasure.Erasure.
Require Import Peregrine.erasure.ErasureTyped.
Require Import Peregrine.erasure.Transforms.
Require Import Peregrine.serialization.Deserialize.
Require Import Peregrine.serialization.DeserializeCommon.
Require Import Peregrine.serialization.DeserializeConfig.
Require Import Peregrine.serialization.DeserializeEAst.
Require Import Peregrine.serialization.DeserializeExAst.
Require Import Peregrine.serialization.DeserializePAst.
Require Import Peregrine.serialization.DeserializePrimitives.
Require Import Peregrine.serialization.Serialize.
Require Import Peregrine.serialization.SerializeCommon.
Require Import Peregrine.serialization.SerializeCommonComplete.
Require Import Peregrine.serialization.SerializeCommonSound.
Require Import Peregrine.serialization.SerializeComplete.
Require Import Peregrine.serialization.SerializeConfig.
Require Import Peregrine.serialization.SerializeConfigComplete.
Require Import Peregrine.serialization.SerializeConfigSound.
Require Import Peregrine.serialization.SerializeEAst.
Require Import Peregrine.serialization.SerializeEAstComplete.
Require Import Peregrine.serialization.SerializeEAstSound.
Require Import Peregrine.serialization.SerializeExAst.
Require Import Peregrine.serialization.SerializeExAstComplete.
Require Import Peregrine.serialization.SerializeExAstSound.
Require Import Peregrine.serialization.SerializeLambdaANF.
Require Import Peregrine.serialization.SerializeLambdaBoxLocal.
Require Import Peregrine.serialization.SerializeLambdaBoxMut.
Require Import Peregrine.serialization.SerializePAst.
Require Import Peregrine.serialization.SerializePAstComplete.
Require Import Peregrine.serialization.SerializePAstSound.
Require Import Peregrine.serialization.SerializePrimitives.
Require Import Peregrine.serialization.SerializePrimitivesComplete.
Require Import Peregrine.serialization.SerializePrimitivesSound.
Require Import Peregrine.serialization.SerializeSound.
Require Import PeregrineHaskellLib.ExtractionHaskell.
Require Import Stdlib.All.All.
Require Import Stdlib.Arith.Arith.
Require Import Stdlib.Arith.Arith_base.
Require Import Stdlib.Arith.Between.
Require Import Stdlib.Arith.Bool_nat.
Require Import Stdlib.Arith.Cantor.
Require Import Stdlib.Arith.Compare.
Require Import Stdlib.Arith.Compare_dec.
Require Import Stdlib.Arith.EqNat.
Require Import Stdlib.Arith.Euclid.
Require Import Stdlib.Arith.Factorial.
Require Import Stdlib.Arith.PeanoNat.
Require Import Stdlib.Arith.Peano_dec.
Require Import Stdlib.Arith.Wf_nat.
Require Import Stdlib.Arith.Zerob.
Require Import Stdlib.Array.ArrayAxioms.
Require Import Stdlib.Array.PArray.
Require Import Stdlib.Array.PrimArray.
Require Import Stdlib.BinNums.IntDef.
Require Import Stdlib.BinNums.NatDef.
Require Import Stdlib.BinNums.PosDef.
Require Import Stdlib.Bool.Bool.
Require Import Stdlib.Bool.BoolEq.
Require Import Stdlib.Bool.DecBool.
Require Import Stdlib.Bool.IfProp.
Require Import Stdlib.Classes.CEquivalence.
Require Import Stdlib.Classes.CMorphisms.
Require Import Stdlib.Classes.CRelationClasses.
Require Import Stdlib.Classes.DecidableClass.
Require Import Stdlib.Classes.EquivDec.
Require Import Stdlib.Classes.Equivalence.
Require Import Stdlib.Classes.Init.
Require Import Stdlib.Classes.Morphisms.
Require Import Stdlib.Classes.Morphisms_Prop.
Require Import Stdlib.Classes.Morphisms_Relations.
Require Import Stdlib.Classes.RelationClasses.
Require Import Stdlib.Classes.RelationPairs.
Require Import Stdlib.Classes.SetoidClass.
Require Import Stdlib.Classes.SetoidDec.
Require Import Stdlib.Classes.SetoidTactics.
Require Import Stdlib.Compat.AdmitAxiom.
Require Import Stdlib.Compat.Coq818.
Require Import Stdlib.Compat.Coq819.
Require Import Stdlib.Compat.Coq820.
Require Import Stdlib.Compat.Stdlib818.
Require Import Stdlib.FSets.FMapAVL.
Require Import Stdlib.FSets.FMapFacts.
Require Import Stdlib.FSets.FMapFullAVL.
Require Import Stdlib.FSets.FMapInterface.
Require Import Stdlib.FSets.FMapList.
Require Import Stdlib.FSets.FMapPositive.
Require Import Stdlib.FSets.FMapWeakList.
Require Import Stdlib.FSets.FMaps.
Require Import Stdlib.FSets.FSetAVL.
Require Import Stdlib.FSets.FSetBridge.
Require Import Stdlib.FSets.FSetCompat.
Require Import Stdlib.FSets.FSetDecide.
Require Import Stdlib.FSets.FSetEqProperties.
Require Import Stdlib.FSets.FSetFacts.
Require Import Stdlib.FSets.FSetInterface.
Require Import Stdlib.FSets.FSetList.
Require Import Stdlib.FSets.FSetPositive.
Require Import Stdlib.FSets.FSetProperties.
Require Import Stdlib.FSets.FSetToFiniteSet.
Require Import Stdlib.FSets.FSetWeakList.
Require Import Stdlib.FSets.FSets.
Require Import Stdlib.Floats.FloatAxioms.
Require Import Stdlib.Floats.FloatClass.
Require Import Stdlib.Floats.FloatLemmas.
Require Import Stdlib.Floats.FloatOps.
Require Import Stdlib.Floats.Floats.
Require Import Stdlib.Floats.PrimFloat.
Require Import Stdlib.Floats.SpecFloat.
Require Import Stdlib.Init.Byte.
Require Import Stdlib.Init.Datatypes.
Require Import Stdlib.Init.Decimal.
Require Import Stdlib.Init.Hexadecimal.
Require Import Stdlib.Init.Logic.
Require Import Stdlib.Init.Ltac.
Require Import Stdlib.Init.Nat.
Require Import Stdlib.Init.Notations.
Require Import Stdlib.Init.Number.
Require Import Stdlib.Init.Peano.
Require Import Stdlib.Init.Prelude.
Require Import Stdlib.Init.Specif.
Require Import Stdlib.Init.Sumbool.
Require Import Stdlib.Init.Tactics.
Require Import Stdlib.Init.Tauto.
Require Import Stdlib.Init.Wf.
Require Import Stdlib.Lists.List.
Require Import Stdlib.Lists.ListDec.
Require Import Stdlib.Lists.ListDef.
Require Import Stdlib.Lists.ListSet.
Require Import Stdlib.Lists.ListTactics.
Require Import Stdlib.Logic.Adjointification.
Require Import Stdlib.Logic.Berardi.
Require Import Stdlib.Logic.ChoiceFacts.
Require Import Stdlib.Logic.Classical.
Require Import Stdlib.Logic.ClassicalChoice.
Require Import Stdlib.Logic.ClassicalDescription.
Require Import Stdlib.Logic.ClassicalEpsilon.
Require Import Stdlib.Logic.ClassicalFacts.
Require Import Stdlib.Logic.ClassicalUniqueChoice.
Require Import Stdlib.Logic.Classical_Pred_Type.
Require Import Stdlib.Logic.Classical_Prop.
Require Import Stdlib.Logic.ConstructiveEpsilon.
Require Import Stdlib.Logic.Decidable.
Require Import Stdlib.Logic.Description.
Require Import Stdlib.Logic.Diaconescu.
Require Import Stdlib.Logic.Epsilon.
Require Import Stdlib.Logic.Eqdep.
Require Import Stdlib.Logic.EqdepFacts.
Require Import Stdlib.Logic.Eqdep_dec.
Require Import Stdlib.Logic.ExtensionalFunctionRepresentative.
Require Import Stdlib.Logic.ExtensionalityFacts.
Require Import Stdlib.Logic.FunctionalExtensionality.
Require Import Stdlib.Logic.HLevels.
Require Import Stdlib.Logic.Hurkens.
Require Import Stdlib.Logic.IndefiniteDescription.
Require Import Stdlib.Logic.JMeq.
Require Import Stdlib.Logic.ProofIrrelevance.
Require Import Stdlib.Logic.ProofIrrelevanceFacts.
Require Import Stdlib.Logic.PropExtensionality.
Require Import Stdlib.Logic.PropExtensionalityFacts.
Require Import Stdlib.Logic.PropFacts.
Require Import Stdlib.Logic.RelationalChoice.
Require Import Stdlib.Logic.SetIsType.
Require Import Stdlib.Logic.SetoidChoice.
Require Import Stdlib.Logic.StrictProp.
Require Import Stdlib.Logic.WKL.
Require Import Stdlib.Logic.WeakFan.
Require Import Stdlib.MSets.MSetAVL.
Require Import Stdlib.MSets.MSetDecide.
Require Import Stdlib.MSets.MSetEqProperties.
Require Import Stdlib.MSets.MSetFacts.
Require Import Stdlib.MSets.MSetGenTree.
Require Import Stdlib.MSets.MSetInterface.
Require Import Stdlib.MSets.MSetList.
Require Import Stdlib.MSets.MSetPositive.
Require Import Stdlib.MSets.MSetProperties.
Require Import Stdlib.MSets.MSetRBT.
Require Import Stdlib.MSets.MSetToFiniteSet.
Require Import Stdlib.MSets.MSetWeakList.
Require Import Stdlib.MSets.MSets.
Require Import Stdlib.NArith.BinNat.
Require Import Stdlib.NArith.BinNatDef.
Require Import Stdlib.NArith.NArith.
Require Import Stdlib.NArith.NArith_base.
Require Import Stdlib.NArith.Ndec.
Require Import Stdlib.NArith.Ndiv_def.
Require Import Stdlib.NArith.Ngcd_def.
Require Import Stdlib.NArith.Nnat.
Require Import Stdlib.NArith.Nsqrt_def.
Require Import Stdlib.Numbers.AltBinNotations.
Require Import Stdlib.Numbers.BinNums.
Require Import Stdlib.Numbers.Cyclic.Abstract.CyclicAxioms.
Require Import Stdlib.Numbers.Cyclic.Abstract.DoubleType.
Require Import Stdlib.Numbers.Cyclic.Abstract.NZCyclic.
Require Import Stdlib.Numbers.Cyclic.Int63.CarryType.
Require Import Stdlib.Numbers.Cyclic.Int63.Cyclic63.
Require Import Stdlib.Numbers.Cyclic.Int63.PrimInt63.
Require Import Stdlib.Numbers.Cyclic.Int63.Ring63.
Require Import Stdlib.Numbers.Cyclic.Int63.Sint63.
Require Import Stdlib.Numbers.Cyclic.Int63.Sint63Axioms.
Require Import Stdlib.Numbers.Cyclic.Int63.Uint63.
Require Import Stdlib.Numbers.Cyclic.Int63.Uint63Axioms.
Require Import Stdlib.Numbers.DecimalFacts.
Require Import Stdlib.Numbers.DecimalN.
Require Import Stdlib.Numbers.DecimalNat.
Require Import Stdlib.Numbers.DecimalPos.
Require Import Stdlib.Numbers.DecimalQ.
Require Import Stdlib.Numbers.DecimalR.
Require Import Stdlib.Numbers.DecimalString.
Require Import Stdlib.Numbers.DecimalZ.
Require Import Stdlib.Numbers.HexadecimalFacts.
Require Import Stdlib.Numbers.HexadecimalN.
Require Import Stdlib.Numbers.HexadecimalNat.
Require Import Stdlib.Numbers.HexadecimalPos.
Require Import Stdlib.Numbers.HexadecimalQ.
Require Import Stdlib.Numbers.HexadecimalR.
Require Import Stdlib.Numbers.HexadecimalString.
Require Import Stdlib.Numbers.HexadecimalZ.
Require Import Stdlib.Numbers.Integer.Abstract.ZAdd.
Require Import Stdlib.Numbers.Integer.Abstract.ZAddOrder.
Require Import Stdlib.Numbers.Integer.Abstract.ZAxioms.
Require Import Stdlib.Numbers.Integer.Abstract.ZBase.
Require Import Stdlib.Numbers.Integer.Abstract.ZBits.
Require Import Stdlib.Numbers.Integer.Abstract.ZDivEucl.
Require Import Stdlib.Numbers.Integer.Abstract.ZDivFloor.
Require Import Stdlib.Numbers.Integer.Abstract.ZDivTrunc.
Require Import Stdlib.Numbers.Integer.Abstract.ZGcd.
Require Import Stdlib.Numbers.Integer.Abstract.ZLcm.
Require Import Stdlib.Numbers.Integer.Abstract.ZLt.
Require Import Stdlib.Numbers.Integer.Abstract.ZMaxMin.
Require Import Stdlib.Numbers.Integer.Abstract.ZMul.
Require Import Stdlib.Numbers.Integer.Abstract.ZMulOrder.
Require Import Stdlib.Numbers.Integer.Abstract.ZParity.
Require Import Stdlib.Numbers.Integer.Abstract.ZPow.
Require Import Stdlib.Numbers.Integer.Abstract.ZProperties.
Require Import Stdlib.Numbers.Integer.Abstract.ZSgnAbs.
Require Import Stdlib.Numbers.Integer.Binary.ZBinary.
Require Import Stdlib.Numbers.Integer.NatPairs.ZNatPairs.
Require Import Stdlib.Numbers.NaryFunctions.
Require Import Stdlib.Numbers.NatInt.NZAdd.
Require Import Stdlib.Numbers.NatInt.NZAddOrder.
Require Import Stdlib.Numbers.NatInt.NZAxioms.
Require Import Stdlib.Numbers.NatInt.NZBase.
Require Import Stdlib.Numbers.NatInt.NZBits.
Require Import Stdlib.Numbers.NatInt.NZDiv.
Require Import Stdlib.Numbers.NatInt.NZDomain.
Require Import Stdlib.Numbers.NatInt.NZGcd.
Require Import Stdlib.Numbers.NatInt.NZLog.
Require Import Stdlib.Numbers.NatInt.NZMul.
Require Import Stdlib.Numbers.NatInt.NZMulOrder.
Require Import Stdlib.Numbers.NatInt.NZOrder.
Require Import Stdlib.Numbers.NatInt.NZParity.
Require Import Stdlib.Numbers.NatInt.NZPow.
Require Import Stdlib.Numbers.NatInt.NZProperties.
Require Import Stdlib.Numbers.NatInt.NZSqrt.
Require Import Stdlib.Numbers.Natural.Abstract.NAdd.
Require Import Stdlib.Numbers.Natural.Abstract.NAddOrder.
Require Import Stdlib.Numbers.Natural.Abstract.NAxioms.
Require Import Stdlib.Numbers.Natural.Abstract.NBase.
Require Import Stdlib.Numbers.Natural.Abstract.NBits.
Require Import Stdlib.Numbers.Natural.Abstract.NDefOps.
Require Import Stdlib.Numbers.Natural.Abstract.NDiv.
Require Import Stdlib.Numbers.Natural.Abstract.NDiv0.
Require Import Stdlib.Numbers.Natural.Abstract.NGcd.
Require Import Stdlib.Numbers.Natural.Abstract.NIso.
Require Import Stdlib.Numbers.Natural.Abstract.NLcm.
Require Import Stdlib.Numbers.Natural.Abstract.NLcm0.
Require Import Stdlib.Numbers.Natural.Abstract.NLog.
Require Import Stdlib.Numbers.Natural.Abstract.NMaxMin.
Require Import Stdlib.Numbers.Natural.Abstract.NMulOrder.
Require Import Stdlib.Numbers.Natural.Abstract.NOrder.
Require Import Stdlib.Numbers.Natural.Abstract.NParity.
Require Import Stdlib.Numbers.Natural.Abstract.NPow.
Require Import Stdlib.Numbers.Natural.Abstract.NProperties.
Require Import Stdlib.Numbers.Natural.Abstract.NSqrt.
Require Import Stdlib.Numbers.Natural.Abstract.NStrongRec.
Require Import Stdlib.Numbers.Natural.Abstract.NSub.
Require Import Stdlib.Numbers.Natural.Binary.NBinary.
Require Import Stdlib.Numbers.NumPrelude.
Require Import Stdlib.PArith.BinPos.
Require Import Stdlib.PArith.BinPosDef.
Require Import Stdlib.PArith.PArith.
Require Import Stdlib.PArith.POrderedType.
Require Import Stdlib.PArith.Pnat.
Require Import Stdlib.Program.Basics.
Require Import Stdlib.Program.Combinators.
Require Import Stdlib.Program.Equality.
Require Import Stdlib.Program.Program.
Require Import Stdlib.Program.Subset.
Require Import Stdlib.Program.Syntax.
Require Import Stdlib.Program.Tactics.
Require Import Stdlib.Program.Utils.
Require Import Stdlib.Program.Wf.
Require Import Stdlib.Program.WfExtensionality.
Require Import Stdlib.QArith.QArith.
Require Import Stdlib.QArith.QArith_base.
Require Import Stdlib.QArith.QOrderedType.
Require Import Stdlib.QArith.Qabs.
Require Import Stdlib.QArith.Qcabs.
Require Import Stdlib.QArith.Qcanon.
Require Import Stdlib.QArith.Qfield.
Require Import Stdlib.QArith.Qminmax.
Require Import Stdlib.QArith.Qpower.
Require Import Stdlib.QArith.Qreduction.
Require Import Stdlib.QArith.Qring.
Require Import Stdlib.QArith.Qround.
Require Import Stdlib.Reals.Abstract.ConstructiveAbs.
Require Import Stdlib.Reals.Abstract.ConstructiveLUB.
Require Import Stdlib.Reals.Abstract.ConstructiveLimits.
Require Import Stdlib.Reals.Abstract.ConstructiveMinMax.
Require Import Stdlib.Reals.Abstract.ConstructivePower.
Require Import Stdlib.Reals.Abstract.ConstructiveReals.
Require Import Stdlib.Reals.Abstract.ConstructiveRealsMorphisms.
Require Import Stdlib.Reals.Abstract.ConstructiveSum.
Require Import Stdlib.Reals.Alembert.
Require Import Stdlib.Reals.AltSeries.
Require Import Stdlib.Reals.ArithProp.
Require Import Stdlib.Reals.Binomial.
Require Import Stdlib.Reals.Cauchy.ConstructiveCauchyAbs.
Require Import Stdlib.Reals.Cauchy.ConstructiveCauchyReals.
Require Import Stdlib.Reals.Cauchy.ConstructiveCauchyRealsMult.
Require Import Stdlib.Reals.Cauchy.ConstructiveExtra.
Require Import Stdlib.Reals.Cauchy.ConstructiveRcomplete.
Require Import Stdlib.Reals.Cauchy.PosExtra.
Require Import Stdlib.Reals.Cauchy.QExtra.
Require Import Stdlib.Reals.Cauchy_prod.
Require Import Stdlib.Reals.ClassicalConstructiveReals.
Require Import Stdlib.Reals.ClassicalDedekindReals.
Require Import Stdlib.Reals.Cos_plus.
Require Import Stdlib.Reals.Cos_rel.
Require Import Stdlib.Reals.DiscrR.
Require Import Stdlib.Reals.Exp_prop.
Require Import Stdlib.Reals.Integration.
Require Import Stdlib.Reals.MVT.
Require Import Stdlib.Reals.Machin.
Require Import Stdlib.Reals.NewtonInt.
Require Import Stdlib.Reals.Nsatz.
Require Import Stdlib.Reals.PSeries_reg.
Require Import Stdlib.Reals.PartSum.
Require Import Stdlib.Reals.Qreals.
Require Import Stdlib.Reals.RIneq.
Require Import Stdlib.Reals.RList.
Require Import Stdlib.Reals.ROrderedType.
Require Import Stdlib.Reals.R_Ifp.
Require Import Stdlib.Reals.R_sqr.
Require Import Stdlib.Reals.R_sqrt.
Require Import Stdlib.Reals.Ranalysis.
Require Import Stdlib.Reals.Ranalysis1.
Require Import Stdlib.Reals.Ranalysis2.
Require Import Stdlib.Reals.Ranalysis3.
Require Import Stdlib.Reals.Ranalysis4.
Require Import Stdlib.Reals.Ranalysis5.
Require Import Stdlib.Reals.Ranalysis_reg.
Require Import Stdlib.Reals.Ratan.
Require Import Stdlib.Reals.Raxioms.
Require Import Stdlib.Reals.Rbase.
Require Import Stdlib.Reals.Rbasic_fun.
Require Import Stdlib.Reals.Rcomplete.
Require Import Stdlib.Reals.Rdefinitions.
Require Import Stdlib.Reals.Rderiv.
Require Import Stdlib.Reals.Reals.
Require Import Stdlib.Reals.Rfunctions.
Require Import Stdlib.Reals.Rgeom.
Require Import Stdlib.Reals.RiemannInt.
Require Import Stdlib.Reals.RiemannInt_SF.
Require Import Stdlib.Reals.Rlimit.
Require Import Stdlib.Reals.Rlogic.
Require Import Stdlib.Reals.Rminmax.
Require Import Stdlib.Reals.Rpow_def.
Require Import Stdlib.Reals.Rpower.
Require Import Stdlib.Reals.Rprod.
Require Import Stdlib.Reals.Rregisternames.
Require Import Stdlib.Reals.Rseries.
Require Import Stdlib.Reals.Rsigma.
Require Import Stdlib.Reals.Rsqrt_def.
Require Import Stdlib.Reals.Rtopology.
Require Import Stdlib.Reals.Rtrigo.
Require Import Stdlib.Reals.Rtrigo1.
Require Import Stdlib.Reals.Rtrigo_alt.
Require Import Stdlib.Reals.Rtrigo_calc.
Require Import Stdlib.Reals.Rtrigo_def.
Require Import Stdlib.Reals.Rtrigo_facts.
Require Import Stdlib.Reals.Rtrigo_fun.
Require Import Stdlib.Reals.Rtrigo_reg.
Require Import Stdlib.Reals.Runcountable.
Require Import Stdlib.Reals.SeqProp.
Require Import Stdlib.Reals.SeqSeries.
Require Import Stdlib.Reals.SplitAbsolu.
Require Import Stdlib.Reals.SplitRmult.
Require Import Stdlib.Reals.Sqrt_reg.
Require Import Stdlib.Reals.Zfloor.
Require Import Stdlib.Relations.Operators_Properties.
Require Import Stdlib.Relations.Relation_Definitions.
Require Import Stdlib.Relations.Relation_Operators.
Require Import Stdlib.Relations.Relations.
Require Import Stdlib.Setoids.Setoid.
Require Import Stdlib.Sets.Classical_sets.
Require Import Stdlib.Sets.Constructive_sets.
Require Import Stdlib.Sets.Cpo.
Require Import Stdlib.Sets.Ensembles.
Require Import Stdlib.Sets.Finite_sets.
Require Import Stdlib.Sets.Finite_sets_facts.
Require Import Stdlib.Sets.Image.
Require Import Stdlib.Sets.Infinite_sets.
Require Import Stdlib.Sets.Integers.
Require Import Stdlib.Sets.Multiset.
Require Import Stdlib.Sets.Partial_Order.
Require Import Stdlib.Sets.Permut.
Require Import Stdlib.Sets.Powerset.
Require Import Stdlib.Sets.Powerset_Classical_facts.
Require Import Stdlib.Sets.Powerset_facts.
Require Import Stdlib.Sets.Relations_1.
Require Import Stdlib.Sets.Relations_1_facts.
Require Import Stdlib.Sets.Relations_2.
Require Import Stdlib.Sets.Relations_2_facts.
Require Import Stdlib.Sets.Relations_3.
Require Import Stdlib.Sets.Relations_3_facts.
Require Import Stdlib.Sets.Uniset.
Require Import Stdlib.Sorting.CPermutation.
Require Import Stdlib.Sorting.Heap.
Require Import Stdlib.Sorting.Mergesort.
Require Import Stdlib.Sorting.PermutEq.
Require Import Stdlib.Sorting.PermutSetoid.
Require Import Stdlib.Sorting.Permutation.
Require Import Stdlib.Sorting.SetoidList.
Require Import Stdlib.Sorting.SetoidPermutation.
Require Import Stdlib.Sorting.Sorted.
Require Import Stdlib.Sorting.Sorting.
Require Import Stdlib.Streams.StreamMemo.
Require Import Stdlib.Streams.Streams.
Require Import Stdlib.Strings.Ascii.
Require Import Stdlib.Strings.BinaryString.
Require Import Stdlib.Strings.Byte.
Require Import Stdlib.Strings.HexString.
Require Import Stdlib.Strings.OctalString.
Require Import Stdlib.Strings.PString.
Require Import Stdlib.Strings.PrimString.
Require Import Stdlib.Strings.PrimStringAxioms.
Require Import Stdlib.Strings.String.
Require Import Stdlib.Structures.BoolOrder.
Require Import Stdlib.Structures.DecidableType.
Require Import Stdlib.Structures.DecidableTypeEx.
Require Import Stdlib.Structures.Equalities.
Require Import Stdlib.Structures.EqualitiesFacts.
Require Import Stdlib.Structures.GenericMinMax.
Require Import Stdlib.Structures.OrderedType.
Require Import Stdlib.Structures.OrderedTypeAlt.
Require Import Stdlib.Structures.OrderedTypeEx.
Require Import Stdlib.Structures.Orders.
Require Import Stdlib.Structures.OrdersAlt.
Require Import Stdlib.Structures.OrdersEx.
Require Import Stdlib.Structures.OrdersFacts.
Require Import Stdlib.Structures.OrdersLists.
Require Import Stdlib.Structures.OrdersTac.
Require Import Stdlib.Unicode.Utf8.
Require Import Stdlib.Unicode.Utf8_core.
Require Import Stdlib.Vectors.Bvector.
Require Import Stdlib.Vectors.Fin.
Require Import Stdlib.Vectors.FinFun.
Require Import Stdlib.Vectors.Vector.
Require Import Stdlib.Vectors.VectorDef.
Require Import Stdlib.Vectors.VectorEq.
Require Import Stdlib.Vectors.VectorSpec.
Require Import Stdlib.Wellfounded.Disjoint_Union.
Require Import Stdlib.Wellfounded.Inclusion.
Require Import Stdlib.Wellfounded.Inverse_Image.
Require Import Stdlib.Wellfounded.Lexicographic_Exponentiation.
Require Import Stdlib.Wellfounded.Lexicographic_Product.
Require Import Stdlib.Wellfounded.List_Extension.
Require Import Stdlib.Wellfounded.Transitive_Closure.
Require Import Stdlib.Wellfounded.Union.
Require Import Stdlib.Wellfounded.Well_Ordering.
Require Import Stdlib.Wellfounded.Wellfounded.
Require Import Stdlib.ZArith.BinInt.
Require Import Stdlib.ZArith.BinIntDef.
Require Import Stdlib.ZArith.Int.
Require Import Stdlib.ZArith.Wf_Z.
Require Import Stdlib.ZArith.ZArith.
Require Import Stdlib.ZArith.ZArith_base.
Require Import Stdlib.ZArith.ZArith_dec.
Require Import Stdlib.ZArith.Zabs.
Require Import Stdlib.ZArith.Zbitwise.
Require Import Stdlib.ZArith.Zbool.
Require Import Stdlib.ZArith.Zcompare.
Require Import Stdlib.ZArith.Zcomplements.
Require Import Stdlib.ZArith.Zdiv.
Require Import Stdlib.ZArith.Zdiv_facts.
Require Import Stdlib.ZArith.Zeuclid.
Require Import Stdlib.ZArith.Zeven.
Require Import Stdlib.ZArith.Zgcd_alt.
Require Import Stdlib.ZArith.Zhints.
Require Import Stdlib.ZArith.Zmax.
Require Import Stdlib.ZArith.Zmin.
Require Import Stdlib.ZArith.Zminmax.
Require Import Stdlib.ZArith.Zmisc.
Require Import Stdlib.ZArith.Znat.
Require Import Stdlib.ZArith.Znumtheory.
Require Import Stdlib.ZArith.Zorder.
Require Import Stdlib.ZArith.Zpow_alt.
Require Import Stdlib.ZArith.Zpow_def.
Require Import Stdlib.ZArith.Zpow_facts.
Require Import Stdlib.ZArith.Zpower.
Require Import Stdlib.ZArith.Zquot.
Require Import Stdlib.ZArith.Zwf.
Require Import Stdlib.ZArith.auxiliary.
Require Import Stdlib.btauto.Algebra.
Require Import Stdlib.btauto.Btauto.
Require Import Stdlib.btauto.Reflect.
Require Import Stdlib.derive.Derive.
Require Import Stdlib.extraction.ExtrHaskellBasic.
Require Import Stdlib.extraction.ExtrHaskellNatInt.
Require Import Stdlib.extraction.ExtrHaskellNatInteger.
Require Import Stdlib.extraction.ExtrHaskellNatNum.
Require Import Stdlib.extraction.ExtrHaskellString.
Require Import Stdlib.extraction.ExtrHaskellZInt.
Require Import Stdlib.extraction.ExtrHaskellZInteger.
Require Import Stdlib.extraction.ExtrHaskellZNum.
Require Import Stdlib.extraction.ExtrOCamlFloats.
Require Import Stdlib.extraction.ExtrOCamlInt63.
Require Import Stdlib.extraction.ExtrOCamlPArray.
Require Import Stdlib.extraction.ExtrOCamlPString.
Require Import Stdlib.extraction.ExtrOcamlBasic.
Require Import Stdlib.extraction.ExtrOcamlChar.
Require Import Stdlib.extraction.ExtrOcamlIntConv.
Require Import Stdlib.extraction.ExtrOcamlNatBigInt.
Require Import Stdlib.extraction.ExtrOcamlNatInt.
Require Import Stdlib.extraction.ExtrOcamlNativeString.
Require Import Stdlib.extraction.ExtrOcamlString.
Require Import Stdlib.extraction.ExtrOcamlZBigInt.
Require Import Stdlib.extraction.ExtrOcamlZInt.
Require Import Stdlib.extraction.Extraction.
Require Import Stdlib.funind.FunInd.
Require Import Stdlib.funind.Recdef.
Require Import Stdlib.micromega.DeclConstant.
Require Import Stdlib.micromega.DeclConstantZ.
Require Import Stdlib.micromega.Env.
Require Import Stdlib.micromega.EnvRing.
Require Import Stdlib.micromega.Fourier.
Require Import Stdlib.micromega.Fourier_util.
Require Import Stdlib.micromega.Lia.
Require Import Stdlib.micromega.Lqa.
Require Import Stdlib.micromega.Lra.
Require Import Stdlib.micromega.OrderedRing.
Require Import Stdlib.micromega.Psatz.
Require Import Stdlib.micromega.QMicromega.
Require Import Stdlib.micromega.RMicromega.
Require Import Stdlib.micromega.Refl.
Require Import Stdlib.micromega.RingMicromega.
Require Import Stdlib.micromega.Tauto.
Require Import Stdlib.micromega.VarMap.
Require Import Stdlib.micromega.ZArith_hints.
Require Import Stdlib.micromega.ZCoeff.
Require Import Stdlib.micromega.ZMicromega.
Require Import Stdlib.micromega.Zify.
Require Import Stdlib.micromega.ZifyBool.
Require Import Stdlib.micromega.ZifyClasses.
Require Import Stdlib.micromega.ZifyComparison.
Require Import Stdlib.micromega.ZifyInst.
Require Import Stdlib.micromega.ZifyN.
Require Import Stdlib.micromega.ZifyNat.
Require Import Stdlib.micromega.ZifyPow.
Require Import Stdlib.micromega.ZifySint63.
Require Import Stdlib.micromega.ZifyUint63.
Require Import Stdlib.micromega.Ztac.
Require Import Stdlib.nsatz.NsatzTactic.
Require Import Stdlib.omega.OmegaLemmas.
Require Import Stdlib.omega.PreOmega.
Require Import Stdlib.rtauto.Bintree.
Require Import Stdlib.rtauto.Rtauto.
Require Import Stdlib.setoid_ring.Algebra_syntax.
Require Import Stdlib.setoid_ring.ArithRing.
Require Import Stdlib.setoid_ring.BinList.
Require Import Stdlib.setoid_ring.Cring.
Require Import Stdlib.setoid_ring.Field.
Require Import Stdlib.setoid_ring.Field_tac.
Require Import Stdlib.setoid_ring.Field_theory.
Require Import Stdlib.setoid_ring.InitialRing.
Require Import Stdlib.setoid_ring.Integral_domain.
Require Import Stdlib.setoid_ring.NArithRing.
Require Import Stdlib.setoid_ring.Ncring.
Require Import Stdlib.setoid_ring.Ncring_initial.
Require Import Stdlib.setoid_ring.Ncring_polynom.
Require Import Stdlib.setoid_ring.Ncring_tac.
Require Import Stdlib.setoid_ring.RealField.
Require Import Stdlib.setoid_ring.Ring.
Require Import Stdlib.setoid_ring.Ring_base.
Require Import Stdlib.setoid_ring.Ring_polynom.
Require Import Stdlib.setoid_ring.Ring_tac.
Require Import Stdlib.setoid_ring.Ring_theory.
Require Import Stdlib.setoid_ring.Rings_Q.
Require Import Stdlib.setoid_ring.Rings_R.
Require Import Stdlib.setoid_ring.Rings_Z.
Require Import Stdlib.setoid_ring.ZArithRing.
Require Import Stdlib.ssr.ssrbool.
Require Import Stdlib.ssr.ssrclasses.
Require Import Stdlib.ssr.ssreflect.
Require Import Stdlib.ssr.ssrfun.
Require Import Stdlib.ssr.ssrsetoid.
Require Import Stdlib.ssr.ssrunder.
Require Import Stdlib.ssrmatching.ssrmatching.
